# /monitoring/grafana/datasources/prometheus.yml
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: rag_app_prometheus_ds # ID ÚNICA Y EXPLÍCITA
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: false 